version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: banking
      MYSQL_USER: user_one
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: avows04032024
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local