version: '3.3'
services:
  db:
    image: mysql:latest
    container_name: avows
    environment:
      MYSQL_DATABASE: 'banking'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:

